
project_id = "kqemgnbqjrqepzkigfcx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
port = 54322

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.start-booking]
verify_jwt = true

[functions.booking-status]
verify_jwt = true

[functions.stop-booking]
verify_jwt = true

[functions.booking-webhook]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
